name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o tcp-tunnel-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o tcp-tunnel-windows-amd64.exe
          GOOS=darwin GOARCH=amd64 go build -o tcp-tunnel-darwin-amd64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tcp-tunnel-linux-amd64
            tcp-tunnel-windows-amd64.exe
            tcp-tunnel-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 